library(dada2)
st1 <- readRDS("/home/larteag7/Banana/May-06/Gissel/seqtab.rds")
st2 <- readRDS("/home/larteag7/Banana/May-06/Luisa/seqtab.rds")
st.all <- mergeSequenceTables(st1, st2)
seqtab <- removeBimeraDenovo(st.all, method="consensus", multithread=TRUE)
tax <- assignTaxonomy(seqtab, "/home/larteag7/Banana/May-06/silva_nr_v128_train_set.fa.gz", multithread=TRUE)
tax <- addSpecies(tax, "/home/larteag7/Banana/May-06/silva_species_assignment_v128.fa.gz")
saveRDS(seqtab, "/home/larteag7/Banana/May-06/seqtab_final.rds")
saveRDS(tax, "/home/larteag7/Banana/May-06/tax_final.rds")
